
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 29 19:09:23 CST 2020
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int nada = 26;
  public static final int Parentesis_c = 15;
  public static final int CLASS = 5;
  public static final int Parentesis_a = 14;
  public static final int ComaChar = 23;
  public static final int INT = 9;
  public static final int ComaFloat = 25;
  public static final int CHAR = 8;
  public static final int PRIVATE = 4;
  public static final int RETURN = 12;
  public static final int ERROR = 27;
  public static final int ComaInt = 21;
  public static final int Llave_c = 17;
  public static final int ComaString = 24;
  public static final int PUBLIC = 3;
  public static final int Coma = 20;
  public static final int Llave_a = 16;
  public static final int P_coma = 19;
  public static final int STRING = 10;
  public static final int FLOAT = 11;
  public static final int Cadena = 13;
  public static final int EOF = 0;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int ComaDouble = 22;
  public static final int VOID = 6;
  public static final int name = 18;
  public static final int DOUBLE = 7;
}

